// import "./js/variables.js";
// import "./js/primiteves.js";
// import "./js/toString.js";
// import "./js/toNumber.js";
// import "./js/toBoolean.js";
// import "./js/avtoCheck.js";
// import "./js/false-values.js";
// import './js/math.js';
// import './js/branching.js';
import './js/cycles.js';
// import './js/function.js';
